### ISSUE TITLE
Feature Request : Remain resources option

### ISSUE THREAD

**Issue by otaki-ryuta** [k1LoW/certman#1]
ACM often fails automatic validation when it renews certificate.
In order to prepare to validate manually, I want to remain resources.

http://docs.aws.amazon.com/ja_jp/acm/latest/userguide/managed-renewal.html#how-manual-domain-validation-works

For example, if `--remain-resources` option is specified in `request` subcommand some resources(SES, S3 and Route 53) aren't removed.

**Comment by k1LoW** [comment]
Hi @otaki-ryuta !
Thank you for good request.

> For example, if --remain-resources option is specified in request subcommand some resources(SES, S3 and Route 53) aren't removed.

Nice!

**Comment by k1LoW** [comment]
Hi @otaki-ryuta !
Support `--remain-resources` option at v0.2.0. 

Regards
