### ISSUE TITLE
[Route53] Create MX Record Set (us-east-1) fails because it conflicts with the CNAME record.

### ISSUE THREAD

**Issue by kitsunde** [k1LoW/certman#12]
This *might* be happening because my apex domain is an alias. I didn't run into this specific issue on other domains.

```bash
$ AWS_DEFAULT_REGION=us-east-1 certman request www.venilia.co
NOTICE! Your selected region is *us-east-1*. Certman create certificate on *us-east-1*. OK? Yes
NOTICE! When requesting, Certman replace Active Receipt Rule Set. OK? Yes
[✔] [ACM] Check Certificate (us-east-1) (successfull)
[✔] [Route53] Check Hosted Zone (us-east-1) (successfull)
[✔] [Route53] Check TXT Record (us-east-1) (successfull)
[✔] [Route53] Check MX Record (us-east-1) (successfull)
[✔] [S3] Create Bucket for SES inbound (us-east-1) (successfull)
[✔] [SES] Create Domain Identity (us-east-1) (successfull)
[✔] [Route53] Create TXT Record Set to verify Domain Identity (us-east-1) (successfull)
[✔] [SES] Check Domain Identity Status *verified* (us-east-1) (successfull)
[/] [Route53] Create MX Record Set (us-east-1)
Error: RRSet of type MX with DNS name www.venilia.co. is not permitted because a conflicting RRSet of type  CNAME with the same DNS name already exists in zone venilia.co.
[✖] [Route53] Create MX Record Set (us-east-1) (error)
[✔] [Route53] Delete TXT Record Set (us-east-1) (successfull)
[✔] [SES] Delete Verified Domain Identiry (us-east-1) (successfull)
[✔] [S3] Delete Bucket (us-east-1) (successfull)
Done.

certificate_arn:
```

My records on this domain:

<img width="700" alt="screenshot 2017-04-11 15 32 08" src="https://cloud.githubusercontent.com/assets/48965/24897583/1456215a-1ecc-11e7-9fbf-6e46eed5024c.png">

**Comment by kitsunde** [comment]
Ah I was under the impression that the MX records would be set on the root, so the issue is unsurprisingly what the error message says. CNAME's don't allow for other records on the same node. I can work around this particular case by changing my CNAME to an A alias.

Maybe it should be possible to set the MX records on the root instead. Since I quite often have sites setup before SSL is added.

**Comment by k1LoW** [comment]
Hi @kitsunde !
I think this issue fixed by #15 . How about you?

**Comment by kitsunde** [comment]
@k1LoW Nah that's a special case on `www`. If I have an existing CNAME on `blog` it'll still blow up.

**Comment by kitsunde** [comment]
You could just say it's by design, have a check before trying to set the MX record to see if there's a CNAME already.

Alternatively it could be nice to check if there's MX records on the apex automatically when finding a CNAME and if there aren't, switch the email_domain apex instead.

**Comment by k1LoW** [comment]
@kitsunde 
Thank you! I understand.
