### ISSUE TITLE
Intermittently no verification email is received.

### ISSUE THREAD

**Issue by kitsunde** [k1LoW/certman#20]
There seem to be some race condition between SES reporting receiving is setup and being able to receive emails. Maybe it's because of DNS propagation, or maybe it's because the reported time isn't true.

So I have to manually re-sent the activation email, otherwise it seems like I need to re-run it anywhere between 2 and 10 times. 

I think it would be helpful if we both paused for some seconds of a grace period in creating the certificate, and retried sending the verification email every say 30 seconds or minute or whatever seems reasonable.

For instance this is a case where I didn't receive the activation email:

<img width="787" alt="screenshot 2017-04-19 04 21 03" src="https://cloud.githubusercontent.com/assets/48965/25151682/0914751a-24b9-11e7-80ad-57cfd1653df1.png">
<img width="1041" alt="screenshot 2017-04-19 04 21 09" src="https://cloud.githubusercontent.com/assets/48965/25151683/093f0eb0-24b9-11e7-9dd5-3970ed3fd26f.png">

Even though the certificate was created 2 seconds after SES receiving became available.

**Comment by k1LoW** [comment]
Hi @kitsunde . Thank you for your report.

> I think it would be helpful if we both paused for some seconds of a grace period in creating the certificate, and retried sending the verification email every say 30 seconds or minute or whatever seems reasonable.

It's nice idea! 

I'll implement it
